apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: mad-trivy-scanner
spec:
  description: |-
    Trivy is a simple and comprehensive scanner for vulnerabilities in container images,file systems ,and Git repositories, as well as for configuration issues.
    This task can be used to scan for vulnenrabilities on the source code in stand alone mode.
  params:
  - name: ARGS
    description: The Arguments to be passed to Trivy command.
    default:
      - image
      - --insecure
    type: array
  - name: TRIVY_IMAGE
    description: Trivy scanner image to be used
    default: docker.io/aquasec/trivy:latest
    type: string
  - name: IMAGE_PATH
    description: Image or Path to be scanned by trivy.
    default: $(params.target-registry)/$(params.target-namespace)/$(params.app-subdir):$(tasks.clone-repository.results.short-commit)
    type: string
  - name: AIR_GAPPED_ENABLED
    description: a flag enabling Air-Gapped mode
    default: "false"
    type: string
  steps:
  - args:
    - $(params.ARGS)
    computeResources: {}
    image: $(params.TRIVY_IMAGE)
    name: trivy-scan
    script: |
      #!/usr/bin/env sh
        cmd="trivy $* "
        if [ "$(params.AIR_GAPPED_ENABLED)" = "true" ]; then
          echo "Air-Gapped mode enabled"
          TRIVY_TEMP_DIR=$(mktemp -d)
          trivy --cache-dir "$TRIVY_TEMP_DIR" image --download-db-only
          tar -cf ./db.tar.gz -C "$TRIVY_TEMP_DIR/db" metadata.json trivy.db
          rm -rf "$TRIVY_TEMP_DIR"
          mkdir -p "$HOME"/.cache/trivy/db
          tar xvf ./db.tar.gz -C "$HOME"/.cache/trivy/db
          cmd="${cmd}--skip-update "
        fi
        cmd="${cmd}$(params.IMAGE_PATH)"
        echo "Running trivy task with command below"
        echo "$cmd"
        eval "$cmd"
    workingDir: $(workspaces.manifest-dir.path)
  workspaces:
  - name: manifest-dir
